### ISSUE TITLE
Publish chart & image to private GitHub registry

### ISSUE THREAD

**Issue by richardcase** [rancher-sandbox/rancher-turtles#117]
### What would you like to be added (User Story)?

As a developer
I want the Rancher Turtles chart published to a private registry that is easily accesible
So that they can be used for testing

### Detailed Description

We will publish the chart and images to 2 places:

1. Rancher Prime Registry (#81)
2. Private GHCR (this issue)

### Label(s) to be applied

/kind feature

**Comment by furkatgofurov7** [comment]
Some more notes after offline discussion: 

- Rancher Prime Registry #81: update the default image in the chart values yam to point to the prime registry. Update the release workflow to tag and push the image to the prime registry. 
- Private GHCR (this issue): we will be re-using the same GHA we currently have since we are publishing charts in the github pages and images in ghcr
- (new): add nightly builds to publish charts and images in ghcr and make them private

**Comment by furkatgofurov7** [comment]
All relevant PRs are merged, @richardcase can this be closed now?
