### ISSUE TITLE
Automatically import a CAPI cluster when its Ready

### ISSUE THREAD

**Issue by richardcase** [rancher-sandbox/rancher-turtles#12]
**Story**

As a Rancher Operator,
I want to automatically import a **Ready** CAPI cluster into Rancher,
So that i can explore the cluster, install applications and perform other tasks like any other imported cluster.

**Description**

The initial poc auto imported the cluster but we need to refactor the code to be more production ready. A few things we need to consider/look at it:
- Should we add a reference to `github.com/rancher/rancher/pkg/apis` so we can use the API types instead of using unstructured.
- We cannot have the Rancher Cluster named the same as the CAPI cluster due to a conflict in the kubeconfig generation. We need to think how we name the new instance, which namespace we place it in.
- Currently we use the import endpoint to get the manifests. Could we use the actual import generation code directly?

**Comment by alexander-demicev** [comment]
Addressing concerns from the description:
- We added a wrapper around rancher object to avoid importing rancher API, there will be problems with dependencies due to usage of forks.
- We create a Rancher cluster with a different name already. We can make a preflight check and ensure there is no Rancher cluster existing with the same name as CAPI cluster but this most likely has to go to UI issues.
- Same dependency problem as above, we have this issue to improve manifest download code https://github.com/rancher-sandbox/rancher-turtles/issues/45 and this PR includes some refactoring around manifest creation to make it more readable https://github.com/rancher-sandbox/rancher-turtles/pull/53

**Comment by alexander-demicev** [comment]
can we close the issue?

**Comment by salasberryfin** [comment]
Closing as this has already been implemented.
