### ISSUE TITLE
[e2e] Stabilize current tests

### ISSUE THREAD

**Issue by richardcase** [rancher-sandbox/rancher-turtles#120]
### What would you like to be added (User Story)?

As a developer
I want stable/consistent e2e tests
So that they give confidence and value to me.

### Detailed Description

The e2e tests can be a bit unstable, lets look into this and make them more stable.

### Label(s) to be applied

/kind feature

**Comment by Danil-Grigorev** [comment]
The source of flakiness in the tests is currently a test on rancher cluster deletion. We should delete v3 cluster instead of v1 object to replicate the behavior the user does from UI. As we are planning to move the test into integration suite, https://github.com/rancher-sandbox/rancher-turtles/pull/138 removes this test case. This issue could be closed after it is merged.

**Comment by Danil-Grigorev** [comment]
Closed by #138

**Comment by richardcase** [comment]
as discussed in stand-up this can be closed
