### ISSUE TITLE
[e2e] Run full e2e periodically and a subset on each PR

### ISSUE THREAD

**Issue by richardcase** [rancher-sandbox/rancher-turtles#121]
### What would you like to be added (User Story)?

As a developer
I want e2e tests that run quickly on PR and still have full coverage daily
So that PRs can be merged quicker but we still have daily testing

### Detailed Description

We need to have 2 e2e GHA workflows

- On PR it executes tests that use Docker as the infra provider
- Periodically 1 time per day run all tests

### Label(s) to be applied

/kind feature

**Comment by furkatgofurov7** [comment]
> We need to have 2 e2e GHA workflows

> On PR it executes tests that use Docker as the infra provider
Periodically 1 time per day run all tests


This can probably be closed since we have now 2 GH workflows, which run:
- [e2e on every PR](https://github.com/rancher-sandbox/rancher-turtles/blob/main/.github/workflows/e2e-every-pr.yaml)
- [e2e nightly](https://github.com/rancher-sandbox/rancher-turtles/blob/main/.github/workflows/e2e-nightly-full.yaml)

**Comment by richardcase** [comment]
This has been completed so closing
