### ISSUE TITLE
kubectl images are not valid in k3s/k3d

### ISSUE THREAD

**Issue by Flou21** [rancher-sandbox/rancher-turtles#280]
## Steps

I have set up a k3d cluster as a testing environment.
And installed the helm chart with the command:

`helm install rancher-turtles turtles/rancher-turtles --version 0.3.0 -n rancher-turtles-system --dependency-update --create-namespace`

## What happened

The image for the `rancher-mutatingwebhook-cleanup` and `rancher-validatingwebhook-cleanup` can not be pulled.

Part of `kubectl describe`:
```
Events:
  Type     Reason         Age                    From     Message
  ----     ------         ----                   ----     -------
  Warning  InspectFailed  5m1s (x742 over 165m)  kubelet  Failed to apply default image tag "rancher/kubectl:v1.27.4+k3s1": couldn't parse image reference "rancher/kubectl:v1.27.4+k3s1": invalid reference format
```

## Explanation

The image tag, that is used is: `{{ .Capabilities.KubeVersion }}`
This works fine for most kubernetes environments, but not all

### What did you expect to happen?

a valid image tag for the jobs should be used

### How to reproduce it?

install turtles in a k3d/k3d cluster

### Rancher Turtles version

0.3.0

### Anything else you would like to add?

I would also like to create a pull request myself to fix the bug.
But I'm not sure how this can / should be improved.

It is of course possible to specify the version of the image in the values file next to `.Values.rancherTurtles.features.rancher-webhook.kubectlImage`, but that would have to be maintained in the future as well

### Label(s) to be applied

/kind bug

**Comment by salasberryfin** [comment]
Hey @Flou21, thanks for taking the time to report this.

We'd love to have you contributing to the project with a fix. Please refer to the [contributing guide](https://docs.rancher-turtles.com/docs/contributing/intro) for PR submission details and how to setup a development environment .

As you described, the `rancher/kubectl` image must have a tag matching the Kubernetes version of the cluster where Rancher Turtles is deployed. We could have a version of the image in the values file for scenarios like k3s but this tag should be populated automatically so that user experience is not affected by this. It should be transparent for those that don't want to modify any values.

If you need help, please don't hesitate to ask!

**Comment by Flou21** [comment]
I have created a pr
I hope the type of solution fits, if not I will gladly change it again
